# Generated by Django 3.2.18 on 2023-04-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20230419_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_cart',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_paid',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
