# Generated by Django 3.2.18 on 2023-04-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20230419_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_paid',
            new_name='stripe_pid',
        ),
    ]
