# Generated by Django 3.2.18 on 2023-04-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_rename_user_order_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='date',
        ),
    ]
