# Generated by Django 3.2.18 on 2023-04-12 18:57

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('friendly_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('mechanism_type', models.CharField(choices=[('quartz', 'Quartz'), ('mechanical', 'Mechanical'), ('automatic', 'Automatic'), ('kinetic', 'Kinetic'), ('digital', 'Digital'), ('solar', 'Solar-powered'), ('smart', 'Smart'), ('other', 'Other')], max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image')),
                ('stock', models.IntegerField(choices=[(0, 'Out of stock '), (1, 'In stock'), (2, 'Running low')], default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watches', to='shop.brand')),
            ],
            options={
                'verbose_name_plural': 'Watches',
                'ordering': ['brand__name', 'name'],
            },
        ),
    ]
