# Generated by Django 3.2.18 on 2023-04-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230417_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color_option',
            new_name='has_color_option',
        ),
    ]
