# Generated by Django 3.2.18 on 2023-04-14 00:34

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_watch_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('friendly_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('stock', models.IntegerField(choices=[(0, 'In stock'), (1, 'Running low'), (2, 'Out of stock')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name_plural': 'Watches'},
        ),
        migrations.RemoveField(
            model_name='watch',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='image',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='price',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='stock',
        ),
        migrations.AddField(
            model_name='watch',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='mechanism_type',
            field=models.CharField(choices=[('quartz', 'Quartz'), ('mechanical', 'Mechanical'), ('automatic', 'Automatic'), ('kinetic', 'Kinetic'), ('digital', 'Digital')], max_length=50),
        ),
        migrations.CreateModel(
            name='WatchStrap',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.product')),
                ('strap_type', models.CharField(choices=[('nato', 'Nato Strap'), ('zulu', 'Zulu Strap'), ('perlon', 'Perlon Strap'), ('leather', 'Leather Strap'), ('rubber', 'Rubber Strap'), ('silicone', 'Silicone Strap'), ('metal', 'Metal Bracelet'), ('leather', 'Leather Strap')], max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Watch Straps',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category'),
        ),
        migrations.AddField(
            model_name='watch',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.product'),
            preserve_default=False,
        ),
    ]
