# Generated by Django 3.2.18 on 2023-04-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230414_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchstrap',
            name='image_url',
        ),
    ]
