# Generated by Django 3.2.18 on 2023-04-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_color_option_product_has_color_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_color_option',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
